<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ecae2b42-f1df-42f5-8621-680cc15941ba</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GovUk.Frontend.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManageEntitlementFunding.Domain\ManageEntitlementFunding.Domain.csproj" />
  </ItemGroup>

</Project>
